// This file is generated by ttrpc-compiler 0.7.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
#![allow(clippy::all)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;
use async_trait::async_trait;

#[derive(Clone)]
pub struct GreeterClient {
    client: ::ttrpc::r#async::Client,
}

impl GreeterClient {
    pub fn new(client: ::ttrpc::r#async::Client) -> Self {
        GreeterClient {
            client,
        }
    }

    pub async fn say_hello(&self, ctx: ttrpc::context::Context, req: &super::image::RpcRequest) -> ::ttrpc::Result<super::image::RpcResponse> {
        let mut cres = super::image::RpcResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "image.Greeter", "say_hello", cres);
    }

    pub async fn get_file(&self, ctx: ttrpc::context::Context, req: &super::image::GetFileRpcRequest) -> ::ttrpc::Result<super::image::GetFileResponse> {
        let mut cres = super::image::GetFileResponse::new();
        ::ttrpc::async_client_request!(self, ctx, req, "image.Greeter", "get_file", cres);
    }
}

struct SayHelloMethod {
    service: Arc<dyn Greeter + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for SayHelloMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, image, RpcRequest, say_hello);
    }
}

struct GetFileMethod {
    service: Arc<dyn Greeter + Send + Sync>,
}

#[async_trait]
impl ::ttrpc::r#async::MethodHandler for GetFileMethod {
    async fn handler(&self, ctx: ::ttrpc::r#async::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<::ttrpc::Response> {
        ::ttrpc::async_request_handler!(self, ctx, req, image, GetFileRpcRequest, get_file);
    }
}

#[async_trait]
pub trait Greeter: Sync {
    async fn say_hello(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::image::RpcRequest) -> ::ttrpc::Result<super::image::RpcResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/image.Greeter/say_hello is not supported".to_string())))
    }
    async fn get_file(&self, _ctx: &::ttrpc::r#async::TtrpcContext, _: super::image::GetFileRpcRequest) -> ::ttrpc::Result<super::image::GetFileResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/image.Greeter/get_file is not supported".to_string())))
    }
}

pub fn create_greeter(service: Arc<dyn Greeter + Send + Sync>) -> HashMap<String, ::ttrpc::r#async::Service> {
    let mut ret = HashMap::new();
    let mut methods = HashMap::new();
    let streams = HashMap::new();

    methods.insert("say_hello".to_string(),
                    Box::new(SayHelloMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    methods.insert("get_file".to_string(),
                    Box::new(GetFileMethod{service: service.clone()}) as Box<dyn ::ttrpc::r#async::MethodHandler + Send + Sync>);

    ret.insert("image.Greeter".to_string(), ::ttrpc::r#async::Service{ methods, streams });
    ret
}
